### ISSUE TITLE
Exit Status code not working

### ISSUE THREAD

**Issue by TheurgicDuke771** [oh-my-fish/theme-zish#5]
Hi,
I have been using this theme for past few weeks, just notice that the exit status is not working.
please check the attached screenshot for the issue. 
I installed it with oh my fish.
Modification made to fish_prompt file are  
`printf '%d' $exit_code` --> `printf ' | %d' $exit_code`
![Screenshot from 2021-09-09 20-10-49](https://user-images.githubusercontent.com/25581767/132708062-cdd9dd6e-06cb-488c-ac1e-5a0c2675a5d5.jpg)

**Comment by scorphus** [comment]
Hi, I'm sorry you're having this issue.

We need more information. Can you please share the output of `type fish_right_prompt`?

Thanks!

**Comment by TheurgicDuke771** [comment]
Hi, please find bellow the output for `type fish_right_prompt`:  

<img width="887" alt="raycast-untitled" src="https://user-images.githubusercontent.com/25581767/132758026-b36e8e1b-6191-4e67-8afa-e18c967c9bf1.png">

**Comment by scorphus** [comment]
Looks like minconda is messing with `fish_right_prompt`. What does `type __fish_right_prompt_orig` tell?

**Comment by scorphus** [comment]
This is what you would expect:

```
┌─<nemo @ 0721d083d985 in ~>
└─<>──» foo                                                                          0 < 20:47:40
fish: Unknown command: foo
┌─<nemo @ 0721d083d985 in ~>
└─<>──» type fish_right_prompt                                                     127 < 20:47:42
fish_right_prompt is a function with definition
# Defined in /home/nemo/.local/share/omf/themes/zish/functions/fish_right_prompt.fish @ line 1
function fish_right_prompt
  set -l exit_code $status
  if test $exit_code -ne 0
    set_color red
  else
    set_color green
  end
  printf '%d' $exit_code
  set_color yellow
  printf ' < %s' (date +%H:%M:%S)
  set_color normal
end
┌─<nemo @ 0721d083d985 in ~>
└─<>──»                                                                              0 < 20:50:26
```

**Comment by TheurgicDuke771** [comment]
Output for `type __fish_right_prompt_orig`:  

![image](https://user-images.githubusercontent.com/25581767/132765787-f494eeee-ed01-4569-9e24-7560f471ad01.png)

**Comment by scorphus** [comment]
Yeah, miniconda is messing with it.

> Hi, please find bellow the output for `type fish_right_prompt`:
> 
> <img alt="raycast-untitled" width="887" src="https://user-images.githubusercontent.com/25581767/132758026-b36e8e1b-6191-4e67-8afa-e18c967c9bf1.png">

The code before `__fish_right_prompt_orig` resets `$status`. Specifically:

![image](https://user-images.githubusercontent.com/2112697/132771660-2d02245d-46f2-4ece-a75f-fe84d10f5fc3.png)

So, when `__fish_right_prompt_orig` runs, it refers to a `$status` that has been set by that `if` and then its body. At such point, `$status` has a new value (which is almost always going to be `0`).

**Comment by TheurgicDuke771** [comment]
Okay.  
Can I change anything thing in the `fish_right_prompt` file so, it will refer the expected exit status code?

**Comment by scorphus** [comment]
As `fish_right_prompt` is called at least one `if` statement after the actual last command you typed, which is the command you want the status displayed for, there's nothing you can change on it to overcome that. At least not without disabling conda's changing of the right prompt: https://github.com/conda/conda/issues/6996#issuecomment-568598640

Once you have it disabled, you can call a previously copy of it inside `fish_right_prompt` as you'll then have `$status" saved as the local variable `$exit_status`.

So, in your `config.fish` you can have for instance:

```fish
# ...

# create a copy of __conda_add_prompt
functions __conda_add_prompt --copy __conda_add_prompt_copy

# reset __conda_add_prompt to an empty function
function __conda_add_prompt; end

# ...
```

Then, you can change `fish_right_prompt` to something like:

```fish
function fish_right_prompt
  set -l exit_code $status
  __conda_add_prompt_copy
  if test $exit_code -ne 0
    set_color red
  else
    set_color green
  end
  printf ' | %d' $exit_code
  set_color yellow
  printf ' < %s' (date +%H:%M:%S)
  set_color normal
end
```

I hope it helps you solve the issue. Please LMK otherwise :slightly_smiling_face:

**Comment by TheurgicDuke771** [comment]
Hi  
I've done the modification but it doesn't seems to be working.
I think this is because the `if` block is still executing even for a blank function.  

My `config.fish` now looks like:  

```fish

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
eval /home/arijit/miniconda3/bin/conda "shell.fish" "hook" $argv | source
# <<< conda initialize <<<

# create a copy of __conda_add_prompt
functions __conda_add_prompt --copy __conda_add_prompt_copy

# reset __conda_add_prompt to an empty function
function __conda_add_prompt; end
```

And `fish_right_prompt.fish` file:  

```fish
function fish_right_prompt
  set -l exit_code $status
  __conda_add_prompt_copy
  if test $exit_code -ne 0
    set_color red
  else
    set_color green
  end
  printf ' | %d' $exit_code
  set_color yellow
  printf ' < %s' (date +%H:%M:%S)
  set_color normal
end
```

And my terminal:  

```
┌─<arijit @ Lenovo-81F4 in ~>
└─<>──» git status                                                                                       (miniconda3) | 0 < 23:56:50
fatal: not a git repository (or any of the parent directories): .git
┌─<arijit @ Lenovo-81F4 in ~>
└─<>──» echo $status                                                                                     (miniconda3) | 0 < 23:57:45
128
┌─<arijit @ Lenovo-81F4 in ~>
└─<>──» type fish_right_prompt                                                                           (miniconda3) | 0 < 23:57:59
fish_right_prompt is a function with definition
# Defined via `source`
function fish_right_prompt
  if not set -q CONDA_LEFT_PROMPT
      __conda_add_prompt
  end
  __fish_right_prompt_orig
end
┌─<arijit @ Lenovo-81F4 in ~>
└─<>──» type __fish_right_prompt_orig                                                                    (miniconda3) | 0 < 23:58:17
__fish_right_prompt_orig is a function with definition
# Defined interactively
function __fish_right_prompt_orig
  set -l exit_code $status
  __conda_add_prompt_copy
  if test $exit_code -ne 0
    set_color red
  else
    set_color green
  end
  printf ' | %d' $exit_code
  set_color yellow
  printf ' < %s' (date +%H:%M:%S)
  set_color normal
end
```

**Comment by scorphus** [comment]
What if you change your `config.fish` to read like the following instead?

```fish
```

**Comment by scorphus** [comment]
What if you change `config.fish` to read like the following?

```fish
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
eval /home/arijit/miniconda3/bin/conda "shell.fish" "hook" $argv | source
# <<< conda initialize <<<

# recover original fish_right_prompt
functions --erase fish_right_prompt
functions __fish_right_prompt_orig --copy fish_right_prompt
```

p.s.: sorry, I didn't intend to close the issue. It seems I'm too used to Ctrl+Shift+Return for adding a new line above while editing text. But on GitHub it comments and closes the issue. :laughing:

**Comment by TheurgicDuke771** [comment]
Thanks :grinning:  
Now it works fine after modifying the `config.fish` .  
One issue virtual environment name was not coming (expected).   
So, I have added the bellow lines in `fish_right_prompt.fish` before printing exit_code:  
```fish
set_color green
printf $CONDA_PROMPT_MODIFIER
```

So, now my terminal :  
```
┌─<arijit @ Lenovo-81F4 in ~>
└─<>──» git status                                                                                       (miniconda3) | 0 < 10:18:12
fatal: not a git repository (or any of the parent directories): .git
┌─<arijit @ Lenovo-81F4 in ~>
└─<>──» echo $status                                                                                   (miniconda3) | 128 < 10:18:28
128
┌─<arijit @ Lenovo-81F4 in ~>
└─<>──» rm qwert.txt                                                                                     (miniconda3) | 0 < 10:18:40
rm: cannot remove 'qwert.txt': No such file or directory
┌─<arijit @ Lenovo-81F4 in ~>
└─<>──» type fish_right_prompt                                                                           (miniconda3) | 1 < 10:18:45
fish_right_prompt is a function with definition
# Defined interactively
function fish_right_prompt
  set -l exit_code $status
  set_color green
  printf $CONDA_PROMPT_MODIFIER
  if test $exit_code -ne 0
    set_color red
  else
    set_color green
  end
  printf ' | %d' $exit_code
  set_color yellow
  printf ' < %s' (date +%H:%M:%S)
  set_color normal
end
┌─<arijit @ Lenovo-81F4 in ~>
└─<>──»                                                                                                  (miniconda3) | 0 < 10:18:52
```
Thanks for your time :smiley:

**Comment by scorphus** [comment]
Awesome! :raised_hands: I'm glad I helped you make it work! :muscle:
